server:

# JmComic settings
jm_comic:
  dir_rule:
    base_dir: "downloads/"

  client:
    impl: html
    retry_times: 1
    postman:
      meta_data:
        proxies: null # e.g., "http://127.0.0.1:7890" or "clash"
    domain:
      html:
        - "jm18c-cvb.net"
        - "jm18c-tyu.net"
        - "18comic.ink"
        - "jmcomic-zzz.one"
        - "jm18c-cvb.org"
        - "jmcomic-zzz.org"

